'use strict';

var allRecipes = [];

var RecipesConstructor = function(name, servings, course){
  this.name = name;
  this.servings = servings;
  this.course = course;
  this.ingredients = [];
  allRecipes.push(this);
};

var IngredientBuilder = function(name, quantity, unitOfMeasure, storeDepartment, location){
  this.name = name;
  this.quantity = quantity;
  this.unitOfMeasure = unitOfMeasure;
  this.storeDepartment = storeDepartment;
  location.ingredients.push(this);
};

var cider = new RecipesConstructor('MJ\'s Mulled Cider', 8, 'beverages');
var ciderIngre = new IngredientBuilder('Apple Juice', 0.5, 'gallon', 'juice',cider);
ciderIngre = new IngredientBuilder('Cider Mate Mulling Spice', 0.25, 'cup', 'spices', cider);
var sangria = new RecipesConstructor('Apple Cider Autumn Sangria', 6, 'beverages');
var sangriaIngre = new IngredientBuilder('cinnamon sticks', 2, 'each', 'spices',sangria);
sangriaIngre = new IngredientBuilder('medium pear', 1, 'each', 'produce', sangria);
sangriaIngre = new IngredientBuilder('medium orange', 1, 'each', 'produce', sangria);
sangriaIngre = new IngredientBuilder('pomegranate seeds', 0.666, 'cup', 'produce', sangria);
sangriaIngre = new IngredientBuilder('bottle white wine', 1, 'bottle', 'liquor', sangria);
sangriaIngre = new IngredientBuilder('apple cider', 2, 'cup', 'juice', sangria);
sangriaIngre = new IngredientBuilder('brandy', 0.5, 'cup', 'liquor', sangria);
sangriaIngre = new IngredientBuilder('orange juice', 0.25, 'juice', 'juice', sangria);
sangriaIngre = new IngredientBuilder('lemon juice', 2, 'tablespoon', 'produce', sangria);
sangriaIngre = new IngredientBuilder('club soda', 1, 'serving', 'juice', sangria);
var punch = new RecipesConstructor('Lusious Slush Punch', 24, 'beverages');
var punchIngre = new IngredientBuilder('white sugar', 2.5, 'cup', 'baking', punch);
punchIngre = new IngredientBuilder('lemon juice', 0.666, 'cup', 'produce', punch);
punchIngre = new IngredientBuilder('orange juice', 1, 'quart', 'juice', punch);
punchIngre = new IngredientBuilder('lemon-lime flavored carbonated beverage', 2, '2-liter bottles', 'juice', punch);
punchIngre = new IngredientBuilder('strawberry flavored mix', 6, 'ounces', 'baking', punch);
punchIngre = new IngredientBuilder('canned pineapple juice', 46, 'fluid ounces', 'juice', punch);
var pecans = new RecipesConstructor('Spiced Pecans', 16, 'appetizers');
var pecanIngre = IngredientBuilder('salt', 4, 'teaspoon', 'spices', pecans);
pecanIngre = IngredientBuilder('cayeene', 0.5, 'teaspoon', 'spices', pecans);
pecanIngre = IngredientBuilder('white pepper', 1, 'teaspoon', 'spices', pecans);
pecanIngre = IngredientBuilder('nutmeg', 1, 'teaspoon', 'spices', pecans);
pecanIngre = IngredientBuilder('cloves', 1, 'teaspoon', 'spices', pecans);
pecanIngre = IngredientBuilder('allspice', 1, 'teaspoon', 'spices', pecans);
pecanIngre = IngredientBuilder('pecan halves', 4, 'cup', 'nuts', pecans);
pecanIngre = IngredientBuilder('butter', 0.25, 'cup', 'dairy', pecans);
pecanIngre = IngredientBuilder('dark maple syrup', 0.333, 'cup', 'condiments', pecans);
var brie = new RecipesConstructor('Apple-Pecan Baked Brie', 10, 'beverages');
var brieIngre = IngredientBuilder('butter', 1, 'tablespoon', 'dairy', brie);
brieIngre = IngredientBuilder('small tart apple', 1, 'each', 'produce', brie);
brieIngre = IngredientBuilder('dried cranberries', 0.333, 'cup', 'produce', brie);
brieIngre = IngredientBuilder('chopped pecans', 0.25, 'cup', 'nuts', brie);
brieIngre = IngredientBuilder('brown sugar', 1, 'tablespoon', 'baking', brie);
brieIngre = IngredientBuilder('ground cinnamon', 0.25, 'teaspoon', 'spices', brie);
brieIngre = IngredientBuilder('ground nutmeg', 1, 'dash', 'spices', brie);
brieIngre = IngredientBuilder('Brie cheese', 8, 'ounces', 'dairy', brie);
brieIngre = IngredientBuilder('crakers', 1, 'assorted', 'other grocery', brie);
var poppers = new RecipesConstructor('Jalapeno Popper Cups', 4, 'beverages');
var poppersIngre = IngredientBuilder('mini phyllo tart shells', 12, 'each', 'frozen', poppers);
poppersIngre = IngredientBuilder('cream cheese', 4, 'ounces', 'dairy', poppers);
poppersIngre = IngredientBuilder('shredded cheddar cheese', 0.5, 'cup', 'dairy', poppers);
poppersIngre = IngredientBuilder('jalapeno peppers', 2, 'each', 'produce', poppers);
poppersIngre = IngredientBuilder('hot pepper sauce', 1, 'tablespoon', 'condiments', poppers);
poppersIngre = IngredientBuilder('bacon bits', 1, 'dash', 'meat', poppers);

// var IngredientsConstructor = function (name, qty, measurementunit, location) {
//   this.name = name;
//   this.quantity = qty;
//   this.measurementunit = measurementunit;
//   this.location = location;
// };

// RecipesConstructor.prototype.ingredientsArrayCreator = function (name, qty, measurementunit, location) {
//   var ingredOne = new IngredientsConstructor (name, qty, measurementunit, location);
//   this.ingredients.push(ingredOne);
// };

// var cider = new RecipesConstructor('MJ\'s Mulled Cider', 8, 'beverages');
// cider.ingredientsArrayCreator('Apple Juice', 0.5, 'gallon', 'juice',cider);
// cider.ingredientsArrayCreator('Cider Mate Mulling Spice', 0.25, 'cup', 'spices', cider);
// var sangria = new RecipesConstructor('Apple Cider Autumn Sangria', 6, 'beverages');
// sangria.ingredientsArrayCreator('cinnamon sticks', 2, 'each', 'spices',sangria);
// sangria.ingredientsArrayCreator('medium pear', 1, 'each', 'produce', sangria);
// sangria.ingredientsArrayCreator('medium orange', 1, 'each', 'produce', sangria);
// sangria.ingredientsArrayCreator('pomegranate seeds', 0.666, 'cup', 'produce', sangria);
// sangria.ingredientsArrayCreator('bottle white wine', 1, 'bottle', 'liquor', sangria);
// sangria.ingredientsArrayCreator('apple cider', 2, 'cup', 'juice', sangria);
// sangria.ingredientsArrayCreator('brandy', 0.5, 'cup', 'liquor', sangria);
// sangria.ingredientsArrayCreator('orange juice', 0.25, 'juice', 'juice', sangria);
// sangria.ingredientsArrayCreator('lemon juice', 2, 'tablespoon', 'produce', sangria);
// sangria.ingredientsArrayCreator('club soda', 1, 'serving', 'juice', sangria);
// var punch = new RecipesConstructor('Lusious Slush Punch', 24, 'beverages');
// punch,ingredientsArrayCreator('white sugar', 2.5, 'cup', 'baking', punch);
// punch,ingredientsArrayCreator('lemon juice', 0.666, 'cup', 'produce', punch);
// punch,ingredientsArrayCreator('orange juice', 1, 'quart', 'juice', punch);
// punch,ingredientsArrayCreator('lemon-lime flavored carbonated beverage', 2, '2-liter bottles', 'juice', punch);
// punch,ingredientsArrayCreator('strawberry flavored mix', 6, 'ounces', 'baking', punch);
// punch,ingredientsArrayCreator('canned pineapple juice', 46, 'fluid ounces', 'juice', punch);
// var pecans = new RecipesConstructor('', , 'beverages');
// pecans.ingredientsArrayCreator('salt', 4, 'teaspoon', 'spices', pecans);
// pecans.ingredientsArrayCreator('cayeene', 0.5, 'teaspoon', 'spices', pecans);
// pecans.ingredientsArrayCreator('white pepper', 1, 'teaspoon', 'spices', pecans);
// pecans.ingredientsArrayCreator('nutmeg', 1, 'teaspoon', 'spices', pecans);
// pecans.ingredientsArrayCreator('cloves', 1, 'teaspoon', 'spices', pecans);
// pecans.ingredientsArrayCreator('allspice', 1, 'teaspoon', 'spices', pecans);
// pecans.ingredientsArrayCreator('pecan halves', 4, 'cup', 'nuts', pecans);
// pecans.ingredientsArrayCreator('butter', 0.25, 'cup', 'dairy', pecans);
// pecans.ingredientsArrayCreator('dark maple syrup', 0.333, 'cup', 'condiments', pecans);
// var brie = new RecipesConstructor('', , 'beverages');
// brie.ingredientsArrayCreator('butter', 1, 'tablespoon', 'dairy', brie);
// brie.ingredientsArrayCreator('small tart apple', 1, 'each', 'produce', brie);
// brie.ingredientsArrayCreator('dried cranberries', 0.333, 'cup', 'other grocery', brie);
// brie.ingredientsArrayCreator('chopped pecans', 0.25, 'cup', 'nuts', brie);
// brie.ingredientsArrayCreator('brown sugar', 1, 'tablespoon', 'baking', brie);
// brie.ingredientsArrayCreator('ground cinnamon', 0.25, 'teaspoon', 'spices', brie);
// brie.ingredientsArrayCreator('ground nutmeg', 1, 'dash', 'spices', brie);
// brie.ingredientsArrayCreator('Brie cheese', 8, 'ounces', 'dairy', brie);
// brie.ingredientsArrayCreator('crakers', 1, 'assorted', 'other grocery', brie);
// var poppers = new RecipesConstructor('Jalapeno Popper Cups', 4, 'beverages');
// poppers.ingredientsArrayCreator('mini phyllo tart shells', 12, 'each', 'frozen', poppers);
// poppers.ingredientsArrayCreator('cream cheese', 4, 'ounces', 'dairy', poppers);
// poppers.ingredientsArrayCreator('shredded cheddar cheese', 0.5, 'cup', 'dairy', poppers);
// poppers.ingredientsArrayCreator('jalapeno peppers', 2, 'each', 'produce', poppers);
// poppers.ingredientsArrayCreator('hot pepper sauce', 1, 'tablespoon', 'condiments', poppers);
// poppers.ingredientsArrayCreator('bacon bits', 1, 'dash', 'meat', poppers);